### ISSUE TITLE
nextjs compatibility - window is not defined SSR

### ISSUE THREAD

**Issue by RitschAlex** [PejmanNik/jikji#19]
I tried to integrate the lib into an nextjs project. While the CSR version of this lib is working fine, the SSR version with the BrowserRouter component is not working.

```
- error node_modules/@jikji/react/lib/index.cjs.js (1:6931) @ eval
- error ReferenceError: window is not defined
    at __webpack_require__ (/home/lain/repos/Typescript/houkoku/.next/server/webpack-runtime.js:33:42)
    at eval (./app/report/page.tsx:7:70)
    at Object.(sc_client)/./app/report/page.tsx (/home/lain/repos/Typescript/houkoku/.next/server/app/report/page.js:283:1)
    at __webpack_require__ (/home/lain/repos/Typescript/houkoku/.next/server/webpack-runtime.js:33:42)
null
```

**Comment by PejmanNik** [comment]
The BrowserRouter is  a very basic implementor of the router and doesn't support SSR, you can use third-party common router component

**Comment by PejmanNik** [comment]
feel free to reopen the issue if you still need help
